# Generated by Django 4.1.2 on 2022-10-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vtwi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vtwiuser",
            name="channel_id",
            field=models.SlugField(blank=True, default="", verbose_name="チャンネルID"),
        ),
    ]
